### PR TITLE
Add “Product” and “Product list” layouts

### PR DESCRIPTION
**Pull request by SSirjes**
Closes: #113 

---

## Some guides for testing:
- [x]  Check if bgpicker, image drop area and page/article image saving works properly in the following layouts:
  - [x]  **Product list**
  - [x]  **Product**
- [x] Check if **Product list** layout works properly everywhere.
- [x] Check if **Product** layout works properly everywhere.
- [x] Check if **Blog & news** layout didn't broke down.
- [x] Check if **Product list** layout works up to second level in menu.
- [x] Check if **Product list** works for _root item_ (first page).
- [x] Check if **Product** works for _root item_ **(first page)**.
- [x] Check if main menu in desktop didn't broke down.
- [x] Check if main menu in mobile didn't broke down.
- [x] Do a small check for all other layouts to see if something got broken.
- [x] If **first page** is used as **Product list**, there's an option to hide _product_ related pages from main menu. Check if that works as intended.

### CODE REVIEW

**Comment by SSirjes** [comment]
* [x] If root item is product list, where product related layouts are hidden in main menu, then common page subpage shows product related menu items in main menu

**Comment by siimha** [comment]
* [x] If you change content text size with design editor then breadcrumbs spacing in all pages & content area line height changes on one product layout page http://recordit.co/HJKfcWVg7T

**Comment by siimha** [comment]
* [x] When you underline link then it add bottom border to content-item box (only preview) & menu breadcrumbs http://recordit.co/Ay4acLtpor

**Comment by siimha** [comment]
* [x] Can not change form_field_label color when you want dark background for example

**Comment by siimha** [comment]
* [x] item-placeholder should not have content link color & content-link-text-transform
screen shot 2018-07-16 at 10 33 18

**Comment by siimha** [comment]
* [x] menu breadcrumbs link has content-link-font-weight & content-link-text-transform

**Pull request merged**
