### PR TITLE
Lang menu style toggleing

### PR DESCRIPTION
**Pull request by kaspar-naaber**
(Issue: #63)

- [x] Adds Settings Editor popover to toggle language menu modes.

### CODE REVIEW

**Comment by SSirjes** [comment]
_Testing result, 15.02.2017_

* [x] **Dropdown** > **Flags only** > in language menu, **there is lot of empty space**.

screen_shot_2017-02-15_at_09_58_33

* [x]  **Dropdown** > **Names only** > language menu is not displayed in preview, sign out view
_Video: http://recordit.co/pv5a8c4aR6_

screen shot 2017-02-15 at 10 45 24


---
* [x] **Expanded menu** > Menu item hover is wrong - can't see menu item (text is too light)
Video: http://recordit.co/RfQB0BJnsu

**Comment by kaspar-naaber** [comment]
I fixed these things. The positiong might not be ideal but if it works more or less then let's merge it. :)

**Comment by SSirjes** [comment]
_Testimine, 3.04.2017_

* [x] Laiendatud menüü > mobiilse menüü tekst ei ole nähtav (on valge)

screen shot 2017-04-03 at 11 41 21

**Comment by SSirjes** [comment]
_Test result, 5.04.2017_

* ~~960px - 975px is 'Setting' button not displayed~~~

_Comment by @kaspar-naaber:_
> Couldn't reproduce in my computer. I will ignore it at the moment and let's check into this when it happens with a real user.

**Pull request merged**
